# Site settings
title: -Resume-
description: WebSite
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Correcha
user_description: Soy un gran admirador del aprendizaje en línea y tomé muchos cursos en plataformas MOOC como Coursera y Udacity. Principalmente en mis áreas de interés, que son el análisis de datos y la informática, pero tomé muchos cursos en otras áreas para ampliar mi conocimiento. Principalmente me gusta Coursera ya que la considero la mejor plataforma MOOC disponible. Mi interés en la ciencia de datos y la visión artificial. <br> Comencé a aprender Machine Learning a medida que utilizamos sus potentes algoritmos en las tareas de identificación de partículas que nos brindan capacidades adicionales para comprender y analizar todos nuestros datos de una mejor manera. Tomé muchos cursos en línea en línea, alrededor de 30 cursos, la mayoría de ellos sobre Machine Learning y Data Science.
user_title: Statistics Student
email: oecorrechag@unal.edu.co
twitter_username: https://twitter.com/RN71943357
github_username:  https://github.com/oecorrechag
#gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
