# Site settings
title: prueba.io
description: Prueba de ejecicion
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Co
user_description: Texto bajo.
user_title: Estadistica Analitica
email: vaness_bunny@live.com.ar
twitter_username: https://twitter.com/Paulichis_zui
github_username:  https://twitter.com/Paulichis_zui
gplus_username:  https://twitter.com/Paulichis_zui

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
