# Site settings
title: -Resume-
description: WebSite
# baseurl: "/particle" # the subpath of your site, e.g. /blog

# User settings
username: Oscar Correcha
user_description: Machine Learning Y Deep Learning
user_title: Statistics - DATA SCIENTIST
email: oecorrechag@unal.edu.co
twitter_username: https://twitter.com/RN71943357
github_username:  https://github.com/oecorrechag

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
