# Site settings
title: Resume
description: Proyectos
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Oscar Correcha
user_description: Estudiante de último semestre de Estadística de la Universidad Nacional de Colombia sede Medellín Facultad de Ciencias, consultor con formación profesional en análisis de datos con conocimientos en modelación estadística, analítica y machine learning.
user_title: Statistics Student
email: oecorrechag@unal.edu.co
twitter_username: https://twitter.com/RN71943357
github_username:  https://github.com/oecorrechag
#gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
